### ISSUE TITLE
humidity formatting

### ISSUE THREAD

**Issue by cweinhofer** [balassy/MMM-RemoteTemperature#5]
Thanks for adding the humidity display. Couldn't ask for much faster than that.

If I added the line
`tempEl.classList = "temp";`
to the temperature section in MMM-RemoteTemperature.js, would that add a class to the temperature number like the class for the humidity number. I'm trying to do some customizing with the CSS.

Also, would it be possible to add a config option to to push the humidity number down to a subsequent line? I have a whole series of sensor readings and I would like to keep them long and skinny along the edge of my mirror.

**Comment by balassy** [comment]
Great idea! I've just released [version 1.2.0](https://github.com/balassy/MMM-RemoteTemperature/releases/tag/v1.2.0) which supports styling all rendered DOM elements via CSS classes. Please check the "Customizing the design" section in the README.

Regarding the multiline rendering: I would prefer to not introduce such an option, because that would conflict with the now introduced CSS class support and would raise additional questions, like where should the icon be displayed? 

Fortunately you can add a line break with standard CSS. Just try adding this to the `css\custom.css` file:
```css
.MMM-RemoteTemperature .temp::after {
  content: "\a";
  white-space: pre;
}
```
What do you think, does that solve your problem?

**Comment by cweinhofer** [comment]
Sorry for the delay in responding. I had to update my sensors in line with the new 1.1 code before I could test this.

The CSS you suggested works great. With that and the classes you added in 1.2, I can do pretty much anything I need.

I think the CSS line break trick might be something others would also be interested in. What would you think about adding it to the README along with the other "Customizing the design" info? I'm happy to create a push request to that effect.

**Comment by cweinhofer** [comment]
And for the reference of others in the future, here is what I was able to do with the new code you added.

Adding this to my custom CSS
```css
.MMM-RemoteTemperature {
	zoom: 0.75;
	line-height: 1em;
	margin-bottom: 10px;
}

.MMM-RemoteTemperature .symbol,
.MMM-RemoteTemperature .humidity,
.MMM-RemoteTemperature .time {
	zoom: 0.75;
}

.MMM-RemoteTemperature .temp::after {
  content: "\a";
  white-space: pre;
}
```

creates a compact multi-sensor layout like this
![2019-02-18-112119_1024x768_scrot](https://user-images.githubusercontent.com/7067427/52924756-662c2180-3371-11e9-9452-cfde6a4ee915.png)

\* if you want to add support for Firefox (for example, for a remote MM session), append `-moz-transform: scale(0.75);` to the `zoom` property
